export const FETCH_CART_ITEMS_REQUEST = 'FETCH_CART_ITEMS_REQUEST';
export const FETCH_CART_ITEMS_SUCCESS = 'FETCHCART_ITEMS_SUCCESS';
export const FETCH_CART_ITEMS_FAILURE = 'FETCH_CART_ITEMS_FAILURE';

export const ADD_CART_ITEMS_REQUEST = 'ADD_CART_ITEMS_REQUEST';
export const ADD_CART_ITEMS_SUCCESS = 'ADD_CART_ITEMS_SUCCESS';
export const ADD_CART_ITEMS_FAILURE = 'ADD_CART_ITEMS_FAILURE';
